### ISSUE TITLE
Server get error

### ISSUE THREAD

**Issue by vinhtq** [olipo186/Git-Auto-Deploy#111]
The server can receive the event but seems it cannot deploy the code

Here is the error I have:
```
2016-06-27 06:18:33,959 [INFO ]  Incoming request from 192.30.252.41:35480
2016-06-27 06:18:33,960 [INFO ]  Handling the request with GitHubRequestParser
2016-06-27 06:18:33,961 [DEBUG]  Received 'push' event from GitHub
2016-06-27 06:18:33,961 [DEBUG]  Push to branch 'refs/heads/master' was fired
2016-06-27 06:18:33,961 [DEBUG]  Event details - ref: refs/heads/master; action:
2016-06-27 06:18:33,962 [INFO ]  192.30.252.41 - code 500, message Unable to process request
2016-06-27 06:18:33,962 [INFO ]  192.30.252.41 - "POST / HTTP/1.1" 500 -

2016-06-27 06:18:33,963 [INFO ]  Exception happened during processing of request from
2016-06-27 06:18:33,963 [INFO ]
2016-06-27 06:18:33,964 [INFO ]  ('192.30.252.41', 35480)
2016-06-27 06:18:33,964 [INFO ]
2016-06-27 06:18:33,964 [ERROR]  Traceback (most recent call last):
2016-06-27 06:18:33,964 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
2016-06-27 06:18:33,964 [ERROR]  self.process_request(request, client_address)
2016-06-27 06:18:33,965 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2016-06-27 06:18:33,965 [ERROR]  self.finish_request(request, client_address)
2016-06-27 06:18:33,965 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2016-06-27 06:18:33,965 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2016-06-27 06:18:33,965 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
2016-06-27 06:18:33,966 [ERROR]  self.handle()
2016-06-27 06:18:33,966 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2016-06-27 06:18:33,966 [ERROR]  self.handle_one_request()
2016-06-27 06:18:33,966 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2016-06-27 06:18:33,966 [ERROR]  method()
2016-06-27 06:18:33,966 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/httpserver.py", line 99, in do_POST
2016-06-27 06:18:33,967 [ERROR]  raise e
2016-06-27 06:18:33,967 [ERROR]  LockFailed: failed to create /var/www/html/test/ubuntu-512mb-sgp1-01.MainThread-2658
```

**Comment by olipo186** [comment]
Could it be a permission error? What user is GAD running as, and does it have write permissions to the path of your repo?

**Comment by vinhtq** [comment]
First time I ran GAD as GAD User Guide then i tried to change to root
```sudo service git-auto-deploy start``` 
but I still get the error.

The repo on github i set as Public for testing.
The permission for my folder on my server is ```www-data:www-data```

**Comment by vinhtq** [comment]
I solved the problem by follow the second way!

**Comment by olipo186** [comment]
Good!
