### ISSUE TITLE
Error after hook has fired

### ISSUE THREAD

**Issue by Kriechi** [olipo186/Git-Auto-Deploy#115]
I'm using Gitlab with a simple push hook to run a deploy script on a server.
After the script has finished, I see these error  messages in the log - and I think it keeps retrying to execute the same hook over and over again with a small timeout or something:

```
2016-06-29 15:49:03,062 [INFO ]  1 commands executed with status; [0]
2016-06-29 15:49:03,062 [DEBUG]  Successfully released lock: /etc/git-auto-deploy/i13-infrastructure/status_running
2016-06-29 15:49:03,062 [INFO ]  1.2.3.4 - "POST / HTTP/1.1" 200 -
2016-06-29 15:49:03,063 [INFO ]  1.2.3.4 - code 500, message Unable to process request
2016-06-29 15:49:03,063 [INFO ]  1.2.3.4 - "POST / HTTP/1.1" 500 -
2016-06-29 15:49:03,063 [INFO ]  ----------------------------------------
2016-06-29 15:49:03,063 [INFO ]
2016-06-29 15:49:03,063 [INFO ]  Exception happened during processing of request from
2016-06-29 15:49:03,063 [INFO ]
2016-06-29 15:49:03,063 [INFO ]  ('1.2.3.4', 57241)
2016-06-29 15:49:03,063 [ERROR]  Traceback (most recent call last):
2016-06-29 15:49:03,063 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2016-06-29 15:49:03,063 [ERROR]  self.process_request(request, client_address)
2016-06-29 15:49:03,063 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2016-06-29 15:49:03,064 [ERROR]  self.finish_request(request, client_address)
2016-06-29 15:49:03,064 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2016-06-29 15:49:03,064 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2016-06-29 15:49:03,064 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
2016-06-29 15:49:03,064 [ERROR]  self.finish()
2016-06-29 15:49:03,064 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
2016-06-29 15:49:03,064 [ERROR]  self.wfile.close()
2016-06-29 15:49:03,064 [ERROR]  File "/usr/lib/python2.7/socket.py", line 283, in close
2016-06-29 15:49:03,064 [ERROR]  self.flush()
2016-06-29 15:49:03,064 [ERROR]  File "/usr/lib/python2.7/socket.py", line 307, in flush
2016-06-29 15:49:03,064 [ERROR]  self._sock.sendall(view[write_offset:write_offset+buffer_size])
2016-06-29 15:49:03,064 [ERROR]  error: [Errno 32] Broken pipe
2016-06-29 15:49:03,064 [INFO ]  ----------------------------------------
```

IP 1.2.3.4 is the Gitlab server.

Maybe this is a problem in Gitlab itself - because if I click the hook test button, I get a nice error-500 page.

Here my git-auto-deploy config:
```
{
        "logfilepath": "/var/log/git-auto-deploy.log",
        "host": "0.0.0.0",
        "port": 8001,
        "repositories": [
          {
            "url": "git@gitlab.example.com:foobar/my-repo.git",
            "branch": "master",
            "remote": "origin",
            "path": "/etc/git-auto-deploy/my-repo",
            "deploy": "sudo /etc/git-auto-deploy/my-repo/update.sh",
            "filters": [
              {
                "object_kind": "push",
                "ref": "refs/heads/master"
              }
            ]
          }
        ]
      }
```

**Comment by vinhtq** [comment]
I had the same error. Please install GAD using repository instead

**Comment by Kriechi** [comment]
I installed GAD 0.3.0 from the ppa repository on Ubuntu xenial.
Or did you mean I should use git-master?

**Comment by olipo186** [comment]
I'm not able to recreate this. @vinhtq, how did you solve this issue?

**Comment by olipo186** [comment]
Could it be a permission error? Does the ```git-auto-deply``` user have write permissions to the local repo path?

**Comment by Kriechi** [comment]
The permissions are fine - it works in some cases. 
The local checkout is updated and the deploy script is executed successfully: `1 commands executed with status; [0]`
It seems the callback of the hook fails to execute. I guess this really is a Gitlab problem, but GAD should probably NOT fail with a weird traceback.

**Comment by vinhtq** [comment]
First time I installed from PPA but seems GAD not working because of the permission.

Then i followed ```Install from repository (recommended for other systems)``` everything works but if i add   more than 3 repos in the config file. I have the error for not find out the user name for git.

**Comment by olipo186** [comment]
Looks like a network related issue, since the TCP connection is cut abruptly. Closing this for now, please reopen if the issue persists.
