### ISSUE TITLE
Error when pull

### ISSUE THREAD

**Issue by ganjarsetia** [olipo186/Git-Auto-Deploy#131]
I got error when pull. Here the log
```
2016-08-29 05:20:37,545 [INFO ]  Branch master set up to track remote branch master from origin.
2016-08-29 05:20:37,545 [INFO ]  Your branch is up-to-date with 'origin/master'.
2016-08-29 05:20:37,545 [ERROR]  Reset branch 'master'
2016-08-29 05:20:37,564 [INFO ]  Repository /var/lib/git-auto-deploy/gitignore successfully initialized
2016-08-29 05:20:37,564 [INFO ]  Starting Git Auto Deploy in daemon mode
2016-08-29 05:20:37,569 [DEBUG]  Successfully cleared lock: /home/ubuntu/project/my-project/status_running
2016-08-29 05:20:37,569 [DEBUG]  Successfully cleared lock: /home/ubuntu/project/my-project/status_waiting
2016-08-29 05:20:37,569 [DEBUG]  Successfully cleared lock: /var/lib/git-auto-deploy/gitignore/status_running
2016-08-29 05:20:37,569 [DEBUG]  Successfully cleared lock: /var/lib/git-auto-deploy/gitignore/status_waiting
2016-08-29 05:20:37,577 [INFO ]  Listening on 0.0.0.0 port 8001
2016-08-29 05:20:50,854 [INFO ]  Incoming request from 52.33.179.42:32929
2016-08-29 05:20:50,856 [INFO ]  Received event from unknown origin.
2016-08-29 05:20:50,856 [INFO ]  Handling the request with GenericRequestParser
2016-08-29 05:20:50,856 [DEBUG]  Received event from unknown origin. Assume generic data format.
2016-08-29 05:20:50,856 [DEBUG]  Event details - ref: master; action:
2016-08-29 05:20:50,857 [INFO ]  52.33.179.42 - code 500, message Unable to process request
2016-08-29 05:20:50,857 [INFO ]  52.33.179.42 - "POST / HTTP/1.1" 500 -
2016-08-29 05:20:50,857 [INFO ]  ----------------------------------------
2016-08-29 05:20:50,857 [INFO ]
2016-08-29 05:20:50,858 [INFO ]  Exception happened during processing of request from
2016-08-29 05:20:50,858 [INFO ]
2016-08-29 05:20:50,858 [INFO ]  ('52.33.179.42', 32929)
2016-08-29 05:20:50,858 [INFO ]
2016-08-29 05:20:50,858 [ERROR]  Traceback (most recent call last):
2016-08-29 05:20:50,858 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
2016-08-29 05:20:50,858 [ERROR]  self.process_request(request, client_address)
2016-08-29 05:20:50,859 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2016-08-29 05:20:50,859 [ERROR]  self.finish_request(request, client_address)
2016-08-29 05:20:50,859 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2016-08-29 05:20:50,859 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2016-08-29 05:20:50,859 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
2016-08-29 05:20:50,859 [ERROR]  self.handle()
2016-08-29 05:20:50,859 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2016-08-29 05:20:50,861 [ERROR]  self.handle_one_request()
2016-08-29 05:20:50,861 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2016-08-29 05:20:50,861 [ERROR]  method()
2016-08-29 05:20:50,861 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/httpserver.py", line 99, in do_POST
2016-08-29 05:20:50,861 [ERROR]  raise e
2016-08-29 05:20:50,861 [ERROR]  LockFailed: failed to create /home/ubuntu/project/my-project/ip-172-31-54-225.MainThread-7232
2016-08-29 05:20:50,862 [INFO ]  ----------------------------------------
2016-08-29 05:20:50,862 [INFO ]
```

-------

Here the config:
```
{
  "logfilepath": "/var/log/git-auto-deploy.log",
  "host": "0.0.0.0",
  "port": 8001,
  "global_deploy": [
    "echo Deploy started!",
    "echo Deploy completed!"
  ],
  "repositories": [
    {
      "url": "git@ec2-52-31-119-42.us-west-2.compute.amazonaws.com:root/my-project.git",
      "branch": "master",
      "remote": "origin",
      "path": "/home/ubuntu/project/my-project",
      "deploy": "echo deploying"
    },
    {
      "url": "https://github.com/github/gitignore",
      "path": "/var/lib/git-auto-deploy/gitignore"
    }
  ]
}
```

OS: Ubuntu 14 LTS on AWS.
I'm install it using APT-GET
I'm using GitLab 6.9.2 e46b644

**Comment by olipo186** [comment]
Hi,

Are you using the latest version of GAD? Please try a apt-get update && apt-get upgrade

**Comment by ganjarsetia** [comment]
@olipo186 No I haven't try it. I cant do apt-get upgrade. I dont want my OS is update to ubuntu 16. I will try uninstall & install it manually.

**Comment by ganjarsetia** [comment]
Manually is working fine. You can close this issue if you want.

**Comment by olipo186** [comment]
Hi,

I think your problem was that GAD did not have write permission to your repository (/home/ubuntu/project/my-project). I have made an improvement on the error message to give more guidance on this.

In your case, adding the user ```git-auto-deploy``` to the group ```ubuntu``` maybe would have solved the issue, depending on how your permissions are setup.

**Comment by ganjarsetia** [comment]
@olipo186 still the same. Same error log too.

here what I tried.
1. `sudo apt-get update`
2. add `git-auto-deploy` to group ubuntu & www-data.
3. install it via apt-get
