### ISSUE TITLE
Error on starting service

### ISSUE THREAD

**Issue by adrianoprospero** [olipo186/Git-Auto-Deploy#139]
Everytime I start the service, I'm getting the following errors. i tried to reinstall GAD, but, after some time, the problem comes back:

```
2016-10-06 13:04:07,459 [ERROR]  Traceback (most recent call last):
2016-10-06 13:04:07,460 [ERROR]  File "/usr/bin/git-auto-deploy", line 9, in <module>
2016-10-06 13:04:07,460 [ERROR]  
2016-10-06 13:04:07,460 [ERROR]  load_entry_point('git-auto-deploy==0.4', 'console_scripts', 'git-auto-deploy')()
2016-10-06 13:04:07,460 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/gitautodeploy.py", line 472, in main
2016-10-06 13:04:07,461 [ERROR]  
2016-10-06 13:04:07,461 [ERROR]  app.setup(config)
2016-10-06 13:04:07,461 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/gitautodeploy.py", line 312, in setup
2016-10-06 13:04:07,461 [ERROR]  
2016-10-06 13:04:07,462 [ERROR]  self.create_pid_file()
2016-10-06 13:04:07,462 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/gitautodeploy.py", line 166, in create_pid_file
2016-10-06 13:04:07,462 [ERROR]  
2016-10-06 13:04:07,462 [ERROR]  with open(self._config['pidfilepath'], 'w') as f:
2016-10-06 13:04:07,462 [ERROR]  IOError
2016-10-06 13:04:07,463 [ERROR]  :
2016-10-06 13:04:07,463 [ERROR]  [Errno 13] Permission denied: '/var/run/git-auto-deploy.pid'
2016-10-06 13:04:07,463 [ERROR]  
```

**Comment by realsby** [comment]
On your /etc/git-auto-deploy.conf.json file first line related with pidfilepath. Change directory and give permissions to that directory.

My git-auto-deploy.conf.json settings : 
  "pidfilepath": "/var/tmp/git-auto-deploy/git-auto-deploy.pid",

And do this:
mkdir /var/tmp/git-auto-deploy/
chown git-auto-deploy:git-auto-deploy /var/tmp/git-auto-deploy/ -R
chmod 777 /var/tmp/git-auto-deploy/ -R

**Comment by adrianoprospero** [comment]
Hi @realsby ,
I tried this and got to start the service, but now the service stop or restart doesn't work...

**Comment by olipo186** [comment]
Hi,

Looks like a problem in your environment/permission setup. Starting and stopping GAD using the "service start/stop" command should be done as root or using sudo, otherwise you'll run into permission issues.

I suggest you reinstall and use the sudo command when starting and stopping. Please reopen if the problem remains.
