### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by boparaiamrit** [olipo186/Git-Auto-Deploy#143]
```
2016-10-20 14:29:21,693 [INFO ]  Exception happened during processing of request from
2016-10-20 14:29:21,693 [INFO ]  
2016-10-20 14:29:21,693 [INFO ]  ('40.84.58.172', 1112)
2016-10-20 14:29:21,693 [INFO ]  
2016-10-20 14:29:21,693 [ERROR]  Traceback (most recent call last):
2016-10-20 14:29:21,693 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2016-10-20 14:29:21,693 [ERROR]  self.process_request(request, client_address)
2016-10-20 14:29:21,693 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2016-10-20 14:29:21,693 [ERROR]  self.finish_request(request, client_address)
2016-10-20 14:29:21,693 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2016-10-20 14:29:21,693 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2016-10-20 14:29:21,693 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2016-10-20 14:29:21,693 [ERROR]  self.handle()
2016-10-20 14:29:21,694 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2016-10-20 14:29:21,694 [ERROR]  self.handle_one_request()
2016-10-20 14:29:21,694 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2016-10-20 14:29:21,694 [ERROR]  method()
2016-10-20 14:29:21,694 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/httpserver.py", line 99, in do_POST
2016-10-20 14:29:21,694 [ERROR]  raise e
2016-10-20 14:29:21,694 [ERROR]  TypeError: execv() arg 2 must contain only strings
2016-10-20 14:29:21,694 [INFO ]  ----------------------------------------
2016-10-20 14:29:21,694 [INFO ]  
```

**Comment by olipo186** [comment]
Hi,

Please provide a set of steps that can reproduce the crash and then reopen the issue.
