### ISSUE TITLE
No handlers could be found for logger "root"

### ISSUE THREAD

**Issue by sureshprasanna70** [olipo186/Git-Auto-Deploy#151]
```
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/GitDeploy/gitautodeploy/__main__.py", line 5, in <module>
    main()
  File "gitautodeploy/gitautodeploy.py", line 456, in main
    file_config = get_config_from_file(config_file_path)
  File "gitautodeploy/cli/config.py", line 188, in get_config_from_file
    config_data = read_json_file(config_file_path)
  File "gitautodeploy/cli/config.py", line 225, in read_json_file
    raise e
ValueError: Extra data: line 21 column 3 - line 23 column 1 (char 459 - 463)
```

**Comment by olipo186** [comment]
Have a look at your config file, looks like it's invalid

**Comment by olipo186** [comment]
Reopen if the issue remains
