### ISSUE TITLE
Centos 6 ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by drsaluml** [olipo186/Git-Auto-Deploy#164]
`Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/home/Git-Auto-Deploy/gitautodeploy/__main__.py", line 2, in <module>
    from gitautodeploy import main
  File "gitautodeploy/gitautodeploy.py", line 17, in <module>
    from .wsserver import WebSocketClientHandlerFactory
ValueError: Attempted relative import in non-package`

Please guide me.

**Comment by olipo186** [comment]
Hi,

Can you run it with Python 2.7? I recently did changes to achieve Python 3.4+ support, which might have resulted in Python 2.7+ beeing needed instead of 2.6+.

**Comment by drsaluml** [comment]
```
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/rh/python27/root/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/Git-Auto-Deploy/gitautodeploy/__main__.py", line 2, in <module>
    from gitautodeploy import main
  File "gitautodeploy/gitautodeploy.py", line 17, in <module>
    from .wsserver import WebSocketClientHandlerFactory
ValueError: Attempted relative import in non-package

```

**Comment by drsaluml** [comment]
I update Python 2.6 to 2.7 it is not work

**Comment by olipo186** [comment]
I think you are invoking GAD thw wrong way, using either ``python gitautodeploy`` or ``python gitautodeploy.py``. You should instead use ``python -m gitautodeploy``.

Please reopen if the problem persists.
