### ISSUE TITLE
incompatible with Autobahn 0.7.0 and up

### ISSUE THREAD

**Issue by ihipop** [olipo186/Git-Auto-Deploy#172]
> Autobahn 0.7.0 and up moved autobahn.websocket to autobahn.twisted.websocket

https://github.com/olipo186/Git-Auto-Deploy/blob/465cb9263fb1ffc9ba2d4a912847322920180caa/gitautodeploy/gitautodeploy.py#L419

https://github.com/olipo186/Git-Auto-Deploy/blob/465cb9263fb1ffc9ba2d4a912847322920180caa/gitautodeploy/gitautodeploy.py#L471

Using Autobahn with 0.7.0 + also has errors

> 2017-03-03 18:26:59,634 [ERROR]  Traceback (most recent call last):
2017-03-03 18:26:59,634 [ERROR]    File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2017-03-03 18:26:59,634 [ERROR]      self.run()
2017-03-03 18:26:59,634 [ERROR]    File "/usr/lib/python2.7/threading.py", line 754, in run
2017-03-03 18:26:59,634 [ERROR]      self.__target(*self.__args, **self.__kwargs)
2017-03-03 18:26:59,634 [ERROR]    File "/usr/lib/python2.7/dist-packages/gitautodeploy/gitautodeploy.py", line 411, in serve_wss
2017-03-03 18:26:59,634 [ERROR]      WebSocketClientHandler = WebSocketClientHandlerFactory(self._config, self._ws_clients, self._event_store, self._server_status)
2017-03-03 18:26:59,635 [ERROR]    File "/usr/lib/python2.7/dist-packages/gitautodeploy/wsserver.py", line 11, in WebSocketClientHandlerFactory
2017-03-03 18:26:59,635 [ERROR]      class WebSocketClientHandler(WebSocketServerProtocol, object):
2017-03-03 18:26:59,635 [ERROR]  TypeError: Error when calling the metaclass bases
2017-03-03 18:26:59,635 [ERROR]      duplicate base class object
2017-03-03 18:26:59,635 [ERROR]

**Comment by ihipop** [comment]
this make ppa package break at Ubuntu 16.04 LTS
