### ISSUE TITLE
cannot perform relative import / Attempted relative import in non-package

### ISSUE THREAD

**Issue by Gunni** [olipo186/Git-Auto-Deploy#175]
```
[U@X gitautodeploy]$ python3 gitautodeploy.py
Traceback (most recent call last):
  File "gitautodeploy.py", line 17, in <module>
    from .wsserver import WebSocketClientHandlerFactory
SystemError: Parent module '' not loaded, cannot perform relative import

[bandit@netlimgt05 gitautodeploy]$ python2
python2    python2.7
[U@X gitautodeploy]$ python2.7 gitautodeploy.py
Traceback (most recent call last):
  File "gitautodeploy.py", line 17, in <module>
    from .wsserver import WebSocketClientHandlerFactory
ValueError: Attempted relative import in non-package
```

**Comment by Letme** [comment]
Did you do:
```
sudo pip install -r requirements.txt
```
? Maybe with correct user/virtual environment?

**Comment by Luke0129** [comment]
Im currently struggling with the same problem, and have installed the packages from requirements.txt.

```
/GitDeploy $ python gitautodeploy
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/KvasirDevelopment/GitDeploy/gitautodeploy/__main__.py", line 2, in <module>
    from gitautodeploy import main
  File "gitautodeploy/gitautodeploy.py", line 17, in <module>
    from .wsserver import WebSocketClientHandlerFactory
ValueError: Attempted relative import in non-package```

**Comment by Letme** [comment]
Can you paste `pip list` output?

**Comment by olipo186** [comment]
Hi,

If you want to run the script manually you'll need to run it as a package using the -m parameter as described in the docs: https://github.com/olipo186/Git-Auto-Deploy#install-from-repository-recommended-for-other-systems
```
python -m gitautodeploy --config config.json
```

**Comment by olipo186** [comment]
Please reopen if the problem persists.
