### ISSUE TITLE
request_body is not defined ?!

### ISSUE THREAD

**Issue by lechup** [olipo186/Git-Auto-Deploy#176]
Just asking, whether ping from Github should return 500 errors?

```
2017-03-27 11:57:46,624 [INFO ]  Starting Git Auto Deploy in daemon mode
2017-03-27 11:57:46,641 [INFO ]  Listening for connections on http://127.0.0.1:8001
2017-03-27 11:58:19,666 [INFO ]  Incoming request from 127.0.0.1:51528
2017-03-27 11:58:19,667 [INFO ]  Handling the request with GitHubRequestParser
2017-03-27 11:58:19,668 [INFO ]  Received 'ping' event from GitHub
2017-03-27 11:58:19,668 [WARNI]  Unable to process request
2017-03-27 11:58:19,669 [INFO ]  ----------------------------------------
2017-03-27 11:58:19,669 [INFO ]  
2017-03-27 11:58:19,669 [INFO ]  Exception happened during processing of request from
2017-03-27 11:58:19,669 [INFO ]  
2017-03-27 11:58:19,669 [INFO ]  ('127.0.0.1', 51528)
2017-03-27 11:58:19,670 [INFO ]  
2017-03-27 11:58:19,670 [ERROR]  Traceback (most recent call last):
2017-03-27 11:58:19,670 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2017-03-27 11:58:19,670 [ERROR]  self.process_request(request, client_address)
2017-03-27 11:58:19,670 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2017-03-27 11:58:19,670 [ERROR]  self.finish_request(request, client_address)
2017-03-27 11:58:19,670 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2017-03-27 11:58:19,671 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2017-03-27 11:58:19,671 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/httpserver.py", line 21, in __init__
2017-03-27 11:58:19,671 [ERROR]  super(WebhookRequestHandler, self).__init__(*args, **kwargs)
2017-03-27 11:58:19,671 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2017-03-27 11:58:19,671 [ERROR]  self.handle()
2017-03-27 11:58:19,671 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2017-03-27 11:58:19,671 [ERROR]  self.handle_one_request()
2017-03-27 11:58:19,672 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2017-03-27 11:58:19,672 [ERROR]  method()
2017-03-27 11:58:19,672 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/httpserver.py", line 200, in do_POST
2017-03-27 11:58:19,672 [ERROR]  raise e
2017-03-27 11:58:19,672 [ERROR]  NameError: global name 'request_body' is not defined
2017-03-27 11:58:19,672 [INFO ]  ----------------------------------------
```

**Comment by lechup** [comment]
The same is for push event...

```
2017-03-27 12:16:23,781 [INFO ]  Incoming request from 127.0.0.1:51532
2017-03-27 12:16:23,788 [INFO ]  Handling the request with GitHubRequestParser
2017-03-27 12:16:23,792 [INFO ]  Received 'push' event from GitHub
2017-03-27 12:16:23,796 [WARNI]  Unable to process request
2017-03-27 12:16:23,799 [INFO ]  ----------------------------------------
2017-03-27 12:16:23,799 [INFO ]  
2017-03-27 12:16:23,799 [INFO ]  Exception happened during processing of request from
2017-03-27 12:16:23,799 [INFO ]  
2017-03-27 12:16:23,800 [INFO ]  ('127.0.0.1', 51532)
2017-03-27 12:16:23,800 [INFO ]  
2017-03-27 12:16:23,800 [ERROR]  Traceback (most recent call last):
2017-03-27 12:16:23,800 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2017-03-27 12:16:23,800 [ERROR]  self.process_request(request, client_address)
2017-03-27 12:16:23,800 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2017-03-27 12:16:23,800 [ERROR]  self.finish_request(request, client_address)
2017-03-27 12:16:23,800 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2017-03-27 12:16:23,800 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2017-03-27 12:16:23,800 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/httpserver.py", line 21, in __init__
2017-03-27 12:16:23,801 [ERROR]  super(WebhookRequestHandler, self).__init__(*args, **kwargs)
2017-03-27 12:16:23,801 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2017-03-27 12:16:23,801 [ERROR]  self.handle()
2017-03-27 12:16:23,801 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2017-03-27 12:16:23,801 [ERROR]  self.handle_one_request()
2017-03-27 12:16:23,801 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2017-03-27 12:16:23,801 [ERROR]  method()
2017-03-27 12:16:23,801 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/httpserver.py", line 200, in do_POST
2017-03-27 12:16:23,801 [ERROR]  raise e
2017-03-27 12:16:23,801 [ERROR]  NameError: global name 'request_body' is not defined
2017-03-27 12:16:23,802 [INFO ]  ----------------------------------------
2017-03-27 12:16:23,802 [INFO ]  
```

**Comment by olipo186** [comment]
Thanks for the bug report. 👍  It seems like this bug affected all GAD setup with GitHub repos that was using the  "secret-token" options.
