### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by khanof89** [olipo186/Git-Auto-Deploy#177]
I am trying to setup auto deploy on my vagrant ubuntu machine whenever I run 

service git-auto-deploy start

I get the following error : 

chown: changing ownership of `/var/run/git-auto-deploy': Operation not permitted
start-stop-daemon: unable to set gid to 116 (Operation not permitted)

and when I try to run as root I get : 

Starting..
No handlers could be found for logger "root"
Traceback (most recent call last):
  File "/usr/bin/git-auto-deploy", line 11, in <module>
    load_entry_point('git-auto-deploy==0.9.1', 'console_scripts', 'git-auto-deploy')()
  File "/usr/lib/python2.7/dist-packages/gitautodeploy/gitautodeploy.py", line 495, in main
    file_config = get_config_from_file(config_file_path)
  File "/usr/lib/python2.7/dist-packages/gitautodeploy/cli/config.py", line 193, in get_config_from_file
    config_data = read_json_file(config_file_path)
  File "/usr/lib/python2.7/dist-packages/gitautodeploy/cli/config.py", line 230, in read_json_file
    raise e
ValueError: No JSON object could be decoded

How do I solve this ?

**Comment by olipo186** [comment]
Hi,

The command ``service git-auto-deploy start`` needs to be run as root. This will start GAD as a daemon process using the script in /etc/init.d. GAD will then run as a different user configured in /etc/init.d/git-auto-deploy. This is the default user:
```
DAEMON_UID="git-auto-deploy"
```

It looks like you have a syntax error in your config file.
