### ISSUE TITLE
Websocket serving results in UnboundLocalError

### ISSUE THREAD

**Issue by TheMegaTB** [olipo186/Git-Auto-Deploy#197]
When setting `wss-enabled: true` in the config running the server results in the following:
```
2017-10-16 11:21:51,347 [ERROR]  Exception in thread Thread-3:
2017-10-16 11:21:51,347 [ERROR]  Traceback (most recent call last):
2017-10-16 11:21:51,347 [ERROR]    File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2017-10-16 11:21:51,347 [ERROR]      self.run()
2017-10-16 11:21:51,347 [ERROR]    File "/usr/lib/python2.7/threading.py", line 754, in run
2017-10-16 11:21:51,347 [ERROR]      self.__target(*self.__args, **self.__kwargs)
2017-10-16 11:21:51,347 [ERROR]    File "gitautodeploy/gitautodeploy.py", line 474, in serve_wss
2017-10-16 11:21:51,347 [ERROR]  UnboundLocalError: local variable 'BindError' referenced before assignment
```

**Comment by asimzeeshan** [comment]
I am also getting the same error in my logs. Anyway to suppress this?

```code
2019-12-10 04:56:40,075 [INFO ]  Starting Git Auto Deploy in daemon mode
2019-12-10 04:56:40,120 [ERROR]  Exception in thread Thread-3:
2019-12-10 04:56:40,122 [ERROR]  Traceback (most recent call last):
2019-12-10 04:56:40,129 [ERROR]    File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2019-12-10 04:56:40,129 [ERROR]      self.run()
2019-12-10 04:56:40,130 [ERROR]    File "/usr/lib/python2.7/threading.py", line 754, in run
2019-12-10 04:56:40,130 [ERROR]      self.__target(*self.__args, **self.__kwargs)
2019-12-10 04:56:40,130 [ERROR]    File "gitautodeploy/gitautodeploy.py", line 474, in serve_wss
2019-12-10 04:56:40,131 [ERROR]  UnboundLocalError: local variable 'BindError' referenced before assignment
```
