### ISSUE TITLE
start failed :  ValueError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by changchichung** [olipo186/Git-Auto-Deploy#215]
any suggestions ??

```
(.ve) 2018-05-25 09:37:21 [Git-Auto-Deploy]$ sudo .ve/bin/pip install -r requirements.txt 
The directory '/home/mini/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mini/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: setuptools>=20.3.1 in ./.ve/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (32.3.1)
Requirement already satisfied: lockfile>=0.12.2 in ./.ve/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.12.2)
(.ve) 2018-05-25 09:37:24 [Git-Auto-Deploy]$ python -m gitautodeploy --config config.json
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/minion/Git-Auto-Deploy/gitautodeploy/__main__.py", line 14, in <module>
    main()
  File "/home/minion/Git-Auto-Deploy/gitautodeploy/gitautodeploy.py", line 676, in main
    init_config(config)
  File "/home/minion/Git-Auto-Deploy/gitautodeploy/cli/config.py", line 355, in init_config
    from ..models import Project
ValueError: attempted relative import beyond top-level package
```

**Comment by necan** [comment]
I got the same issue.

**Comment by Letme** [comment]
Its because of python 3.6, and I managed to fix it with a simple line change propsed in #238 . Feel free to test.
