### ISSUE TITLE
[ERROR]  Exception in thread Thread-9

### ISSUE THREAD

**Issue by denisgorbunov** [olipo186/Git-Auto-Deploy#234]
Added webhook to the project on GitLab(11.5.1) and get an error when pushing:

```
2019-06-19 15:16:23,504 [INFO ]  Handling the request with GitLabRequestParser
2019-06-19 15:16:23,505 [INFO ]  Received 'Push Hook' event from GitLab
2019-06-19 15:16:23,506 [INFO ]  1 candidates matches the request
2019-06-19 15:16:23,506 [INFO ]  1 candidates matches after applying filters
2019-06-19 15:16:23,507 [INFO ]  188.***.***.2 - "POST / HTTP/1.1" 200 -
2019-06-19 15:16:23,508 [INFO ]  Proceeding with 1 candidates
2019-06-19 15:16:23,509 [INFO ]  Running deploy commands
2019-06-19 15:16:23,512 [INFO ]  Updating repository /home/deploy/www/
2019-06-19 15:16:24,030 [INFO ]  From my.domain.com:tag/fin
2019-06-19 15:16:24,031 [INFO ]     78a358b5..cd63a063  master     -> origin/master
2019-06-19 15:16:24,068 [INFO ]  HEAD is now at cd63a063 Merge branch 'dev' into 'master'
2019-06-19 15:16:24,129 [INFO ]  Repository /home/deploy/www/ successfully updated
2019-06-19 15:16:24,130 [INFO ]  Executing 1 deploy commands
2019-06-19 15:16:24,139 [ERROR]  Exception in thread Thread-9:
2019-06-19 15:16:24,139 [ERROR]  Traceback (most recent call last):
2019-06-19 15:16:24,140 [ERROR]    File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2019-06-19 15:16:24,140 [ERROR]      self.run()
2019-06-19 15:16:24,140 [ERROR]    File "/usr/lib/python2.7/threading.py", line 754, in run
2019-06-19 15:16:24,141 [ERROR]      self.__target(*self.__args, **self.__kwargs)
2019-06-19 15:16:24,141 [ERROR]    File "gitautodeploy/models/project.py", line 190, in execute_webhook
2019-06-19 15:16:24,141 [ERROR]    File "gitautodeploy/wrappers/git.py", line 154, in deploy
2019-06-19 15:16:24,142 [ERROR]    File "gitautodeploy/wrappers/process.py", line 25, in call
2019-06-19 15:16:24,142 [ERROR]    File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
2019-06-19 15:16:24,142 [ERROR]      errread, errwrite)
2019-06-19 15:16:24,142 [ERROR]    File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
2019-06-19 15:16:24,143 [ERROR]      raise child_exception
2019-06-19 15:16:24,143 [ERROR]  TypeError: execv() arg 2 must contain only strings
2019-06-19 15:16:24,143 [ERROR]
```

However, the project update itself is in progress. But information about deploy event in WebUI is not updated:

> Running deploy commands

My `config.json`:
```
{
  "http-enabled": false,
  "https-enabled": true,
  "https-host": "0.0.0.0",
  "https-port": 8082,

  "web-ui-enabled": true,
  "web-ui-username": "bla",
  "web-ui-password": "blabla",
  "web-ui-whitelist": ["127.0.0.1"],

  "ssl-key": "~/Git-Auto-Deploy/privkey.pem",  
  "ssl-cert": "~/Git-Auto-Deploy/fullchain.pem",

  "log-file": "~/gitautodeploy.log",

  "pid-file": "~/.gitautodeploy.pid",

  "log-level": "INFO",

  "repositories": [
    {
      "url": "git@my.domain.com:tag/fin.git",
      "branch": "master",
      "remote": "origin",
      "path": "~/www/",
      "deploy": [
        "echo deploying"
      ]
    }
  ]
}
```

**Comment by Letme** [comment]
I think solution was that you should put a string to `"deploy":` instead of array.

**Comment by denisgorbunov** [comment]
> I think solution was that you should put a string to `"deploy":` instead of array.

Yes you are right!
