### ISSUE TITLE
Unable to process request suddenly

### ISSUE THREAD

**Issue by pquerner** [olipo186/Git-Auto-Deploy#236]
It worked fine until recently (caught attention today). We haven't upgraded anything apart from libs on the BitBucket server. Using Bitbucket OnPremise 7.5.0 with this PR https://github.com/olipo186/Git-Auto-Deploy/pull/217

We have not touched the config.json recently.

Stacktrace:

```
2019-07-12 10:07:48,595 [INFO ]  Listening for connections on http://0.0.0.0:8001
2019-07-12 10:08:01,646 [INFO ]  Incoming request from 192.168.1.71:56704
2019-07-12 10:08:01,646 [INFO ]  Handling the request with BitBucketRequestParser
2019-07-12 10:08:01,646 [DEBUG]  Received event from BitBucket
2019-07-12 10:08:01,647 [INFO ]  192.168.1.71 - code 500, message Unable to process request
2019-07-12 10:08:01,647 [INFO ]  192.168.1.71 - "POST / HTTP/1.1" 500 -
2019-07-12 10:08:01,647 [WARNI]  Unable to process request
2019-07-12 10:08:01,647 [INFO ]  ----------------------------------------
2019-07-12 10:08:01,648 [INFO ]  
2019-07-12 10:08:01,648 [INFO ]  Exception happened during processing of request from
2019-07-12 10:08:01,648 [INFO ]  
2019-07-12 10:08:01,648 [INFO ]  ('192.168.1.71', 56704)
2019-07-12 10:08:01,648 [INFO ]  
2019-07-12 10:08:01,648 [ERROR]  Traceback (most recent call last):
2019-07-12 10:08:01,649 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2019-07-12 10:08:01,649 [ERROR]  self.process_request(request, client_address)
2019-07-12 10:08:01,649 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2019-07-12 10:08:01,649 [ERROR]  self.finish_request(request, client_address)
2019-07-12 10:08:01,649 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-07-12 10:08:01,649 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2019-07-12 10:08:01,650 [ERROR]  File "gitautodeploy/httpserver.py", line 22, in __init__
2019-07-12 10:08:01,650 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2019-07-12 10:08:01,650 [ERROR]  self.handle()
2019-07-12 10:08:01,650 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2019-07-12 10:08:01,650 [ERROR]  self.handle_one_request()
2019-07-12 10:08:01,650 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2019-07-12 10:08:01,651 [ERROR]  method()
2019-07-12 10:08:01,651 [ERROR]  File "gitautodeploy/httpserver.py", line 224, in do_POST
2019-07-12 10:08:01,651 [ERROR]  TypeError: sequence item 1: expected string or Unicode, dict found
2019-07-12 10:08:01,651 [INFO ]  ----------------------------------------
2019-07-12 10:08:01,651 [INFO ]  

```

```
2019-07-04 10:02:58,729 [INFO ]   ^   Executing task cleanup
2019-07-04 10:02:58,729 [INFO ]   ^ ^  Ok
2019-07-04 10:02:58,729 [INFO ]   ^   Executing task build
2019-07-04 10:02:58,729 [INFO ]   ^ ^  Ok
2019-07-04 10:02:58,729 [INFO ]  1 commands executed with status; [0]
2019-07-04 10:02:58,730 [DEBUG]  Successfully released lock: /home/ssh_admin/gitautodeploy_repositories/kwk/typo3cms/status_running
2019-07-04 10:02:58,730 [INFO ]  Deploy commands were executed
2019-07-11 17:12:28,297 [INFO ]  Incoming request from 192.168.1.71:55618
2019-07-11 17:12:28,298 [INFO ]  Handling the request with BitBucketRequestParser
2019-07-11 17:12:28,298 [DEBUG]  Received event from BitBucket
2019-07-11 17:12:28,298 [INFO ]  192.168.1.71 - code 500, message Unable to process request
2019-07-11 17:12:28,298 [INFO ]  192.168.1.71 - "POST / HTTP/1.1" 500 -
2019-07-11 17:12:28,299 [WARNI]  Unable to process request
2019-07-11 17:12:28,299 [INFO ]  ----------------------------------------
2019-07-11 17:12:28,299 [INFO ]
2019-07-11 17:12:28,299 [INFO ]  Exception happened during processing of request from
2019-07-11 17:12:28,299 [INFO ]
2019-07-11 17:12:28,299 [INFO ]  ('192.168.1.71', 55618)
2019-07-11 17:12:28,299 [INFO ]
2019-07-11 17:12:28,300 [ERROR]  Traceback (most recent call last):
2019-07-11 17:12:28,300 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2019-07-11 17:12:28,374 [ERROR]  self.process_request(request, client_address)
2019-07-11 17:12:28,374 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2019-07-11 17:12:28,374 [ERROR]  self.finish_request(request, client_address)
2019-07-11 17:12:28,374 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-07-11 17:12:28,374 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2019-07-11 17:12:28,375 [ERROR]  File "gitautodeploy/httpserver.py", line 22, in __init__
2019-07-11 17:12:28,386 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2019-07-11 17:12:28,386 [ERROR]  self.handle()
2019-07-11 17:12:28,386 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2019-07-11 17:12:28,399 [ERROR]  self.handle_one_request()
2019-07-11 17:12:28,399 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2019-07-11 17:12:28,399 [ERROR]  method()
2019-07-11 17:12:28,399 [ERROR]  File "gitautodeploy/httpserver.py", line 224, in do_POST
2019-07-11 17:12:28,400 [ERROR]  TypeError: sequence item 1: expected string or Unicode, dict found
2019-07-11 17:12:28,400 [INFO ]  ----------------------------------------
2019-07-11 17:12:28,400 [INFO ]
```

Request Body:

```
{"eventKey":"repo:refs_changed","date":"2019-07-12T10:08:01+0200","actor":{"name":"P.Querner","emailAddress":"snip","id":102,"displayName":"Pascal Querner","active":true,"slug":"p.querner","type":"NORMAL"},"repository":{"slug":"ext-snip","id":203,"name":"ext-snip","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"AWRW","id":242,"name":"snip","public":false,"type":"NORMAL"},"public":false},"changes":[{"ref":{"id":"refs/heads/master","displayId":"master","type":"BRANCH"},"refId":"refs/heads/master","fromHash":"0385c6038958b5fb776245f53caae0b75f4704b6","toHash":"0385c6038958b5fb776245f53caae0b75f4704b6","type":"UPDATE"}]}
```

Request Header:

```
X-Request-Id: 82864f7a-5743-494c-919a-0b8c363a17d7
Content-Type: application/json; charset=utf-8
X-Event-Key: repo:refs_changed
```

```
Python 2.7.12
git version 2.7.4
```

HTTP requests only.

**Comment by pquerner** [comment]
Now it works again. I did nothing...

```
2019-07-12 15:48:38,533 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2019-07-12 15:48:38,533 [ERROR]  method()
2019-07-12 15:48:38,533 [ERROR]  File "gitautodeploy/httpserver.py", line 224, in do_POST
2019-07-12 15:48:38,534 [ERROR]  TypeError: sequence item 1: expected string or Unicode, dict found
2019-07-12 15:48:38,534 [INFO ]  ----------------------------------------
2019-07-12 15:48:38,534 [INFO ]
2019-07-15 14:32:32,537 [INFO ]  Incoming request from 192.168.1.71:32890
2019-07-15 14:32:32,537 [INFO ]  Handling the request with BitBucketRequestParser
2019-07-15 14:32:32,538 [DEBUG]  Received event from BitBucket
2019-07-15 14:32:32,538 [INFO ]  1 candidates matches the request
2019-07-15 14:32:32,539 [DEBUG]  Filter 'changes.ref.displayId' does not match ('master' != 'develop')
2019-07-15 14:32:32,539 [INFO ]  0 candidates matches after applying filters
2019-07-15 14:32:32,539 [INFO ]  192.168.1.71 - "POST / HTTP/1.1" 200 -
2019-07-15 14:32:40,962 [INFO ]  Incoming request from 192.168.1.71:32896
2019-07-15 14:32:40,962 [INFO ]  Handling the request with BitBucketRequestParser
2019-07-15 14:32:40,963 [DEBUG]  Received event from BitBucket
2019-07-15 14:32:40,963 [INFO ]  1 candidates matches the request
2019-07-15 14:32:40,964 [INFO ]  1 candidates matches after applying filters
2019-07-15 14:32:40,964 [INFO ]  192.168.1.71 - "POST / HTTP/1.1" 200 -
2019-07-15 14:32:40,964 [INFO ]  Proceeding with 1 candidates
2019-07-15 14:32:40,965 [INFO ]  Running deploy commands
2019-07-15 14:32:41,015 [DEBUG]  Successfully obtained lock: /home/ssh_admin/gitautodeploy_repositories/kwk/xxx/status_running
2019-07-15 14:32:41,015 [INFO ]  Updating repository /home/ssh_admin/gitautodeploy_repositories/kwk/xxx
2019-07-15 14:32:41,822 [INFO ]  Von ssh://xxxx
2019-07-15 14:32:41,822 [INFO ]     bfa37ce..d757807  develop    -> origin/develop
2019-07-15 14:32:41,822 [INFO ]     9f487b8..571f709  master     -> origin/master
2019-07-15 14:32:41,846 [INFO ]  HEAD ist jetzt bei 70ba149 #xxxx-14
2019-07-15 14:32:41,886 [INFO ]  Repository /home/ssh_admin/gitautodeploy_repositories/xxx successfully updated
2019-07-15 14:32:41,886 [INFO ]  Executing 1 deploy commands
2019-07-15 14:32:50,049 [INFO ]  ? Executing task update
2019-07-15 14:32:50,050 [INFO ]  ? Ok
2019-07-15 14:32:50,050 [INFO ]  1 commands executed with status; [0]
```
