### ISSUE TITLE
ImportError when installing from PyPi

### ISSUE THREAD

**Issue by MartorSkull** [olipo186/Git-Auto-Deploy#247]
This is the traceback
```python3
Traceback (most recent call last):
  File "/home/touch/venv/bin/git-auto-deploy", line 8, in <module>
    sys.exit(main())
  File "/home/touch/venv/lib/python3.6/site-packages/gitautodeploy/gitautodeploy.py", line 607, in main
    from cli.config import get_config_defaults, get_config_from_environment
ModuleNotFoundError: No module named 'cli'
```

**Comment by Guy293** [comment]
Installing using pip is broken. This library is old and outdated.
Clone it instead. Worked perfectly for me on two different projects.

**Comment by Letme** [comment]
This is python3 incompatibility issue which is solved in #264 . Hopefully after merge also pypi is updated and then this issue can be closed.
