### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ABC'

### ISSUE THREAD

**Issue by JamshidjonKh** [olipo186/Git-Auto-Deploy#253]
Traceback (most recent call last):
  File "/usr/local/bin/git-auto-deploy", line 11, in <module>
    load_entry_point('git-auto-deploy==0.17', 'console_scripts', 'git-auto-deploy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/git_auto_deploy-0.17-py2.7.egg/gitautodeploy/__init__.py", line 3, in <module>
    from .gitautodeploy import *
  File "/usr/local/lib/python2.7/dist-packages/git_auto_deploy-0.17-py2.7.egg/gitautodeploy/gitautodeploy.py", line 24, in <module>
    from .wsserver import WebSocketClientHandlerFactory
  File "/usr/local/lib/python2.7/dist-packages/git_auto_deploy-0.17-py2.7.egg/gitautodeploy/wsserver.py", line 4, in <module>
    from autobahn.websocket import WebSocketServerProtocol
  File "/usr/local/lib/python2.7/dist-packages/autobahn-20.7.1-py2.7.egg/autobahn/websocket/__init__.py", line 28, in <module>
    from autobahn.websocket.types import ConnectionRequest, ConnectionResponse, \
  File "/usr/local/lib/python2.7/dist-packages/autobahn-20.7.1-py2.7.egg/autobahn/websocket/types.py", line 27, in <module>
    from autobahn.util import public
  File "/usr/local/lib/python2.7/dist-packages/autobahn-20.7.1-py2.7.egg/autobahn/util.py", line 41, in <module>
    import txaio
  File "/usr/local/lib/python2.7/dist-packages/txaio-20.4.1-py2.7.egg/txaio/__init__.py", line 29, in <module>
    from txaio.interfaces import IFailedFuture, ILogger
  File "/usr/local/lib/python2.7/dist-packages/txaio-20.4.1-py2.7.egg/txaio/interfaces.py", line 41, in <module>
    class IBatchedTimer(abc.ABC):
AttributeError: 'module' object has no attribute 'ABC'

**Comment by JamshidjonKh** [comment]
Solved:
