### ISSUE TITLE
python --deamon-mode isn't working

### ISSUE THREAD

**Issue by mehdi89** [olipo186/Git-Auto-Deploy#81]
Thank you for the scripts its really helpful

All is working fine in normal mode like if i start process with 
`python gitautodeploy/`

On post push request from github automatically deploying as configuration but, If I start the process daemon mode using this command its not working. As I am using this script in Digital ocean server i need to run the process in daemon mode. 
`python gitautodeploy/ --daemon-mode`

Error are given below 
`----------------------------------------
2016-04-08 17:59:34,275 [INFO ]  
2016-04-08 17:59:34,275 [INFO ]  Exception happened during processing of request from
2016-04-08 17:59:34,275 [INFO ]  
2016-04-08 17:59:34,276 [INFO ]  ('192.30.252.41', 42233)
2016-04-08 17:59:34,276 [INFO ]  
2016-04-08 17:59:34,276 [ERROR]  Traceback (most recent call last):
2016-04-08 17:59:34,276 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
2016-04-08 17:59:34,277 [ERROR]  self.process_request(request, client_address)
2016-04-08 17:59:34,277 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2016-04-08 17:59:34,277 [ERROR]  self.finish_request(request, client_address)
2016-04-08 17:59:34,277 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2016-04-08 17:59:34,278 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2016-04-08 17:59:34,279 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
2016-04-08 17:59:34,280 [ERROR]  self.handle()
2016-04-08 17:59:34,280 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2016-04-08 17:59:34,280 [ERROR]  self.handle_one_request()
2016-04-08 17:59:34,280 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2016-04-08 17:59:34,280 [ERROR]  method()
2016-04-08 17:59:34,280 [ERROR]  File "gitautodeploy/httpserver.py", line 28, in do_POST
2016-04-08 17:59:34,281 [ERROR]  File "gitautodeploy/httpserver.py", line 72, in figure_out_service_from_request
2016-04-08 17:59:34,281 [ERROR]  ImportError: No module named parsers
2016-04-08 17:59:34,281 [INFO ]  ----------------------------------------`

Please help me out to figure and solve this problem. 

Thank you in advance

**Comment by olipo186** [comment]
Hi @mehdi89,

Thank you for the error report. Found the issue and fixed it in https://github.com/olipo186/Git-Auto-Deploy/commit/07da7916f145be8400d71a45aae2733a9bd46641. If you grab the latest copy daemon mode should work as expected. :)

BR,
Oliver

**Comment by mehdi89** [comment]
Hi Oliver

Thank you for quick fix. Its working perfectly.  :)

Mehedi

**Comment by mehdi89** [comment]
Hi **Oliver**

It start now but not deploying on web-hooks trigger. given this error

`----------------------------------------
2016-04-12 09:40:27,641 [INFO ]  
2016-04-12 09:40:27,641 [INFO ]  Exception happened during processing of request from
2016-04-12 09:40:27,642 [INFO ]  
2016-04-12 09:40:27,642 [INFO ]  ('192.30.252.42', 55160)
2016-04-12 09:40:27,642 [INFO ]  
2016-04-12 09:40:27,642 [ERROR]  Traceback (most recent call last):
2016-04-12 09:40:27,642 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
2016-04-12 09:40:27,644 [ERROR]  self.process_request(request, client_address)
2016-04-12 09:40:27,644 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2016-04-12 09:40:27,644 [ERROR]  self.finish_request(request, client_address)
2016-04-12 09:40:27,644 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2016-04-12 09:40:27,644 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2016-04-12 09:40:27,644 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
2016-04-12 09:40:27,645 [ERROR]  self.handle()
2016-04-12 09:40:27,645 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2016-04-12 09:40:27,646 [ERROR]  self.handle_one_request()
2016-04-12 09:40:27,646 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2016-04-12 09:40:27,646 [ERROR]  method()
2016-04-12 09:40:27,646 [ERROR]  File "gitautodeploy/httpserver.py", line 28, in do_POST
2016-04-12 09:40:27,647 [ERROR]  File "gitautodeploy/httpserver.py", line 72, in figure_out_service_from_request
2016-04-12 09:40:27,647 [ERROR]  ImportError: No module named parsers
`

Can you please fix that too. I can't use it now. i also tried to use as service but not working for me. python way is working fine but not daemon mode. if i logoff or disconnected from ssh its not working. 

Thank you 
Mehedi

**Comment by olipo186** [comment]
Hi @mehdi89 

Can you provide me with a copy of your config? Also, what exact command do you use to start GAD?

**Comment by olipo186** [comment]
@mehdi89, the issue should have been fixed in 07da7916f145be8400d71a45aae2733a9bd46641. Were you able to reproduce the issue using the latest version of GAD?

Please reopen or create a new issue if the problem persists.

**Comment by mehdi89** [comment]
Problem solved and working find. Thank you for support
ᐧ

On Sun, Apr 24, 2016 at 8:16 PM, Oliver Poignant <notifications@github.com>
wrote:

> Closed #81 <https://github.com/olipo186/Git-Auto-Deploy/issues/81>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/olipo186/Git-Auto-Deploy/issues/81#event-639050479>
>



-- 


Regards,
*Mehedi Hasan, *

Software Engineer
