### ISSUE TITLE
Use with Deployment Keys?

### ISSUE THREAD

**Issue by pferrel** [olipo186/Git-Auto-Deploy#86]
How do I use my deployment key so the server doesn't cause git to ask for a sign-in?

**Comment by DirectorX** [comment]
You can use git over ssh and add your production server public key to your git account on the web

**Comment by pferrel** [comment]
The github webhook invokes the git-auto-deploy, which tries to pull, it asks for username and password. The public key of the user running git-auto-deploy is the installed github deploy-key. I've double checked this and the webhook secret is blank. Is there some extra config on the git-auto-deploy side? There used to be a different way to use ssh for pulls from github--hmm, is that a clue?

**Comment by pferrel** [comment]
The URL with deploy keys needs to be the github git@github... type, which isn't really a url, so not sure how to configure this in config.json

**Comment by olipo186** [comment]
As mentioned, for git to use SSH keys when pulling, you'll need to use *git over ssh*. This is done by providing the SSH URL (git@github, which is a perfectly fine URL) instead of the HTTPS URL.

Change the URL in config.json to the corresponding SSH URL, then it should work.

**Comment by pferrel** [comment]
I changed `origin master` to use the ssh url for my repo. I added the server user's public key to the deployment keys of the private repo and `git pull origin master` works fine from the CLI. 

```
aml@ip-172-31-16-110:~/actionml.com$ git pull origin master
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From ssh://github.com/actionml/ActionML-Marketing-
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
Updating 10bbbdc..ef1e524
Fast-forward

```

Now in git-auto-deploy it put the following in config, note the repo URL is the same as `origin master` remote URL in my repo that worked from the CLI.

```
{
  "pidfilepath": "~/.gitautodeploy.pid",
  "logfilepath": "~/gitautodeploy.log",
  "host": "0.0.0.0",
  "port": 2357,
  "repositories": [
    {
      "url": "https://github.com/olipo186/Git-Auto-Deploy.git",
      "branch": "master",
      "remote": "origin",
      "path": "~/git-auto-deploy"
    },
    {
      "url": "ssh://git@github.com/actionml/ActionML-Marketing-.git",
      "branch": "master",
      "remote": "origin",
      "path": "~/actionml.com"
    }
  ]
}
```

But when I push changes I get the following error:

```
aml@ip-172-31-16-110:~/git-auto-deploy$ python gitautodeploy
2016-04-12 20:45:07,121 [INFO ]  Using '/home/aml/git-auto-deploy/config.json' as config
2016-04-12 20:45:07,125 [INFO ]  Repository https://github.com/olipo186/Git-Auto-Deploy.git already present
2016-04-12 20:45:07,125 [INFO ]  Repository ssh://git@github.com/actionml/ActionML-Marketing-.git already present
2016-04-12 20:45:07,125 [INFO ]  Git Auto Deploy started
2016-04-12 20:45:07,126 [INFO ]  Successfully cleared lock: /home/aml/git-auto-deploy/status_running
2016-04-12 20:45:07,126 [INFO ]  Successfully cleared lock: /home/aml/git-auto-deploy/status_waiting
2016-04-12 20:45:07,126 [INFO ]  Successfully cleared lock: /home/aml/actionml.com/status_running
2016-04-12 20:45:07,126 [INFO ]  Successfully cleared lock: /home/aml/actionml.com/status_waiting
2016-04-12 20:45:07,135 [INFO ]  Listening on 0.0.0.0 port 2357
2016-04-12 20:45:33,240 [INFO ]  Received event from GitHub
2016-04-12 20:45:33,240 [INFO ]  192.30.252.41 - - [12/Apr/2016 20:45:33] "POST / HTTP/1.1" 200 -

2016-04-12 20:45:33,240 [INFO ]  Received 'push' event from GitHub
2016-04-12 20:45:33,240 [INFO ]  Push to branch 'refs/heads/master' was fired
2016-04-12 20:45:33,240 [INFO ]  Event details - ref: refs/heads/master; action: 
2016-04-12 20:45:33,240 [INFO ]  ----------------------------------------
2016-04-12 20:45:33,240 [INFO ]  
2016-04-12 20:45:33,241 [INFO ]  Exception happened during processing of request from
2016-04-12 20:45:33,241 [INFO ]  
2016-04-12 20:45:33,241 [INFO ]  ('192.30.252.41', 54908)
2016-04-12 20:45:33,241 [INFO ]  
2016-04-12 20:45:33,241 [ERROR]  Traceback (most recent call last):
2016-04-12 20:45:33,241 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
2016-04-12 20:45:33,241 [ERROR]  self.process_request(request, client_address)
2016-04-12 20:45:33,241 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2016-04-12 20:45:33,241 [ERROR]  self.finish_request(request, client_address)
2016-04-12 20:45:33,241 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2016-04-12 20:45:33,241 [ERROR]  self.RequestHandlerClass(request, client_address, self)
2016-04-12 20:45:33,241 [ERROR]  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
2016-04-12 20:45:33,242 [ERROR]  self.handle()
2016-04-12 20:45:33,242 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2016-04-12 20:45:33,242 [ERROR]  self.handle_one_request()
2016-04-12 20:45:33,242 [ERROR]  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2016-04-12 20:45:33,242 [ERROR]  method()
2016-04-12 20:45:33,242 [ERROR]  File "gitautodeploy/httpserver.py", line 50, in do_POST
2016-04-12 20:45:33,242 [ERROR]  logger.warning('Unable to find any of the repository URLs in the config: %s' % ', '.join(repo_urls))
2016-04-12 20:45:33,242 [ERROR]  NameError: global name 'repo_urls' is not defined
```

I looked into the github parser and found it was looking for `ssh_url` in the response body and this was what I found in the body `u'ssh_url': u'git@github.com:actionml/ActionML-Marketing-.git',` so I changed the repository URL in config.json to match but got the same error.

Something in config I am missing?

**Comment by pferrel** [comment]
argh, had to take of the `ssh://` for an exact URL match, damn that is obscure.

**Comment by olipo186** [comment]
I agree, very obscure.

The sample config file have been updated by @toxxin to include an example with a ```ssh://``` URL in PR https://github.com/olipo186/Git-Auto-Deploy/pull/90. The NameError that occurred as part of the error handling when GAD cannot find a matching URL has also been fixed.
