### ISSUE TITLE
GAD breaks between  v0.2.1 ..  v0.2.2

### ISSUE THREAD

**Issue by dforste** [olipo186/Git-Auto-Deploy#92]
It is found when running without the --log-file option. Here is the stacktrace: 
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/git-auto-deploy/gitautodeploy/__main__.py", line 5, in <module>
    main()
  File "gitautodeploy/gitautodeploy.py", line 600, in main
    app.run()
  File "gitautodeploy/gitautodeploy.py", line 507, in run
    log_file_path = os.path.expanduser(self._config['logfilepath'])
  File "/usr/lib/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

It looks like default options have been commented out. This doesn't sound like the root cause. It is just uncovering the issue. 
https://github.com/olipo186/Git-Auto-Deploy/compare/v0.2.1...v0.2.2#diff-57696f53643a33ca14f7fd021378ba75R418

**Comment by olipo186** [comment]
Good catch 👍 Fixed by 8fbe564f94cb54218b32b119a6d41ed241293608 in release [v0.2.4](https://github.com/olipo186/Git-Auto-Deploy/releases/tag/v0.2.4).
